const keywords = [
  "break",
  "case",
  "catch",
  "class",
  "continue",
  "const",
  "constructor",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "finally",
  "for",
  "from",
  "function",
  "get",
  "if",
  "import",
  "in",
  "instanceof",
  "let",
  "new",
  "return",
  "set",
  "static",
  "super",
  "switch",
  "symbol",
  "this",
  "throw",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "async",
  "await",
  "of",
];

const constants = ["true", "false", "null", "undefined", "NaN", "Infinity"];

const builtinObjects = [
  "console",
  "document",
  "window",
  "globalThis",
  "navigator",
  "location",
  "history",
  "screen",
  "self",
  "parent",
  "top",
  "frames",
  "localStorage",
  "sessionStorage",
  "indexedDB",
  "crypto",
  "performance",
  "Math",
  "JSON",
  "Object",
  "Array",
  "String",
  "Number",
  "Boolean",
  "Date",
  "Promise",
  "Map",
  "Set",
  "WeakMap",
  "WeakSet",
  "WeakRef",
  "FinalizationRegistry",
  "Error",
  "TypeError",
  "RangeError",
  "SyntaxError",
  "ReferenceError",
  "URIError",
  "EvalError",
  "AggregateError",
  "RegExp",
  "Symbol",
  "BigInt",
  "Intl",
  "Reflect",
  "Proxy",
  "Atomics",
  "WebAssembly",
  "URL",
  "URLSearchParams",
  "TextEncoder",
  "TextDecoder",
  "AbortController",
  "AbortSignal",
  "FormData",
  "Headers",
  "Request",
  "Response",
  "File",
  "FileReader",
  "Blob",
  "Event",
  "CustomEvent",
  "EventTarget",
  "DOMParser",
  "XMLHttpRequest",
  "Worker",
  "SharedWorker",
  "MessageChannel",
  "BroadcastChannel",
  "MutationObserver",
  "ResizeObserver",
  "IntersectionObserver",
  "Image",
  "Audio",
  "Option",
];

const builtinFunctions = [
  "setTimeout",
  "setInterval",
  "clearTimeout",
  "clearInterval",
  "setImmediate",
  "clearImmediate",
  "queueMicrotask",
  "requestAnimationFrame",
  "cancelAnimationFrame",
  "requestIdleCallback",
  "cancelIdleCallback",
  "fetch",
  "atob",
  "btoa",
  "parseInt",
  "parseFloat",
  "isNaN",
  "isFinite",
  "eval",
  "uneval",
  "escape",
  "unescape",
  "decodeURI",
  "decodeURIComponent",
  "encodeURI",
  "encodeURIComponent",
  "structuredClone",
  "alert",
  "confirm",
  "prompt",
  "open",
  "close",
  "focus",
  "blur",
  "print",
  "postMessage",
  "getComputedStyle",
  "matchMedia",
  "getSelection",
  "reportError",
  "createImageBitmap",
];

const operators = [
  "<=",
  ">=",
  "==",
  "!=",
  "===",
  "!==",
  "=>",
  "+",
  "-",
  "**",
  "*",
  "/",
  "%",
  "++",
  "--",
  "<<",
  "</",
  ">>",
  ">>>",
  "&",
  "|",
  "^",
  "!",
  "~",
  "&&",
  "||",
  "??",
  "?",
  ":",
  "=",
  "+=",
  "-=",
  "*=",
  "**=",
  "/=",
  "%=",
  "<<=",
  ">>=",
  ">>>=",
  "&=",
  "|=",
  "^=",
  "@",
];

function jsLanguage() {
  return {
    defaultToken: "invalid",
    tokenPostfix: ".js",
    keywords,
    constants,
    builtinObjects,
    builtinFunctions,
    operators,
    brackets: [
      ["{", "}", "delimiter.curly"],
      ["[", "]", "delimiter.square"],
      ["(", ")", "delimiter.parenthesis"],
    ],
    symbols: /[=><!~?:&|+\-*\/\^%]+/,
    escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
    digits: /\d+(_+\d+)*/,
    octaldigits: /[0-7]+(_+[0-7]+)*/,
    binarydigits: /[0-1]+(_+[0-1]+)*/,
    hexdigits: /[[0-9a-fA-F]+(_+[0-9a-fA-F]+)*/,
    regexpctl: /[(){}\[\]\$\^|\-*+?\.]/,
    regexpesc: /\\(?:[bBdDfnrstvwWn0\\\/]|@regexpctl|c[A-Z]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4})/,
    tokenizer: {
      root: [{ include: "common" }],
      common: [
        [/(\.)(\s*)([#]?[A-Za-z_$][\w$]*)(\s*)(\()/, ["delimiter", "", "identifier.method", "", "@brackets"]],
        [/(\.)(\s*)([#]?[A-Za-z_$][\w$]*)/, ["delimiter", "", "identifier.property"]],
        [
          /(#?[a-z_$][\w$]*)(\s*)(\()/,
          {
            cases: {
              "$1@keywords": ["keyword", "", "@brackets"],
              "$1@constants": ["constant", "", "@brackets"],
              "$1@builtinFunctions": ["identifier.function", "", "@brackets"],
              "$1@builtinObjects": ["variable.predefined", "", "@brackets"],
              "@default": ["identifier.function", "", "@brackets"],
            },
          },
        ],
        [
          /#?[a-z_$][\w$]*/,
          {
            cases: {
              "@keywords": "keyword",
              "@constants": "constant",
              "@builtinFunctions": "identifier.function",
              "@builtinObjects": "variable.predefined",
              "@default": "identifier",
            },
          },
        ],
        [
          /[A-Z][\w$]*/,
          {
            cases: {
              "@constants": "constant",
              "@builtinObjects": "type.identifier",
              "@builtinFunctions": "identifier.function",
              "@default": "type.identifier",
            },
          },
        ],
        { include: "@whitespace" },
        [/\/(?=([^\\\/]|\\.)+\/([dgimsuy]*)(\s*)(\.|;|,|\)|\]|\}|$))/, { token: "regexp", bracket: "@open", next: "@regexp" }],
        [/[{}()\[\]]/, "@brackets"],
        [/[<>](?!@symbols)/, "@brackets"],
        [/!(?=([^=]|$))/, "operator"],
        [/@symbols/, { cases: { "@operators": "operator", "@default": "" } }],
        [/(@digits)[eE]([\-+]?(@digits))?/, "number.float"],
        [/(@digits)\.(@digits)([eE][\-+]?(@digits))?/, "number.float"],
        [/0[xX](@hexdigits)n?/, "number.hex"],
        [/0[oO]?(@octaldigits)n?/, "number.octal"],
        [/0[bB](@binarydigits)n?/, "number.binary"],
        [/(@digits)n?/, "number"],
        [/[;,]/, "delimiter"],
        [/"([^"\\]|\\.)*$/, "string.invalid"],
        [/'([^'\\]|\\.)*$/, "string.invalid"],
        [/"/, "string", "@string_double"],
        [/'/, "string", "@string_single"],
        [/`/, "string", "@string_backtick"],
      ],
      whitespace: [
        [/[ \t\r\n]+/, "white"],
        [/\/\*\*(?!\/)/, "comment.doc", "@jsdoc"],
        [/\/\*/, "comment", "@comment"],
        [/\/\/.*$/, "comment"],
      ],
      comment: [
        [/[^\/*]+/, "comment"],
        [/\*\//, "comment", "@pop"],
        [/[\/*]/, "comment"],
      ],
      jsdoc: [
        [/[^\/*]+/, "comment.doc"],
        [/\*\//, "comment.doc", "@pop"],
        [/[\/*]/, "comment.doc"],
      ],
      regexp: [
        [/(\{)(\d+(?:,\d*)?)(\})/, ["regexp.escape.control", "regexp.escape.control", "regexp.escape.control"]],
        [/(\[)(\^?)(?=(?:[^\]\\\/]|\\.)+)/, ["regexp.escape.control", { token: "regexp.escape.control", next: "@regexrange" }]],
        [/(\()(\?:|\?=|\?!)/, ["regexp.escape.control", "regexp.escape.control"]],
        [/[()]/, "regexp.escape.control"],
        [/@regexpctl/, "regexp.escape.control"],
        [/[^\\\/]/, "regexp"],
        [/@regexpesc/, "regexp.escape"],
        [/\\\./, "regexp.invalid"],
        [/(\/)([dgimsuy]*)/, [{ token: "regexp", bracket: "@close", next: "@pop" }, "keyword.other"]],
      ],
      regexrange: [
        [/-/, "regexp.escape.control"],
        [/\^/, "regexp.invalid"],
        [/@regexpesc/, "regexp.escape"],
        [/[^\]]/, "regexp"],
        [/\]/, { token: "regexp.escape.control", next: "@pop", bracket: "@close" }],
      ],
      string_double: [
        [/[^\\"]+/, "string"],
        [/@escapes/, "string.escape"],
        [/\\./, "string.escape.invalid"],
        [/"/, "string", "@pop"],
      ],
      string_single: [
        [/[^\\']+/, "string"],
        [/@escapes/, "string.escape"],
        [/\\./, "string.escape.invalid"],
        [/'/, "string", "@pop"],
      ],
      string_backtick: [
        [/\$\{/, { token: "delimiter.bracket", next: "@bracketCounting" }],
        [/[^\\`$]+/, "string"],
        [/@escapes/, "string.escape"],
        [/\\./, "string.escape.invalid"],
        [/`/, "string", "@pop"],
      ],
      bracketCounting: [[/\{/, "@brackets", "@bracketCounting"], [/\}/, "@brackets", "@pop"], { include: "common" }],
    },
  };
}

let registered = false;

export function registerJsSyntax(monaco) {
  if (registered) return;
  registered = true;
  const language = jsLanguage();
  monaco.languages.setMonarchTokensProvider("javascript", language);
  monaco.languages.setMonarchTokensProvider("typescript", { ...language, tokenPostfix: ".ts" });
}
