export function defineJellyfishTheme(monaco) {
  monaco.editor.defineTheme("jellyfish", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "838383", fontStyle: "italic" },
      { token: "string", foreground: "eeff00" },
      { token: "keyword", foreground: "ff0062" },
      { token: "number", foreground: "ff7e34" },
      { token: "constant", foreground: "ff7e34" },
      { token: "regexp", foreground: "89DDFF" },
      { token: "operator", foreground: "89DDFF" },
      { token: "type", foreground: "4EC9B0" },
      { token: "type.identifier", foreground: "4EC9B0" },
      { token: "identifier", foreground: "EEFFFF" },
      { token: "identifier.property", foreground: "9CDCFE" },
      { token: "identifier.method", foreground: "DCDCAA" },
      { token: "identifier.function", foreground: "DCDCAA" },
      { token: "variable", foreground: "EEFFFF" },
      { token: "variable.predefined", foreground: "4EC9B0" },
      { token: "property", foreground: "9CDCFE" },
      { token: "member", foreground: "DCDCAA" },
      { token: "function", foreground: "DCDCAA" },
      { token: "method", foreground: "DCDCAA" },
      { token: "class", foreground: "4EC9B0" },
      { token: "delimiter", foreground: "ffffff" },
      { token: "delimiter.curly", foreground: "FFD700" },
      { token: "delimiter.square", foreground: "DA70D6" },
      { token: "delimiter.parenthesis", foreground: "179FFF" },
      { token: "delimiter.bracket", foreground: "FFD700" },
    ],
    colors: {
      "editor.background": "#0f0021",
      "editor.foreground": "#ffffff",
      "editorLineNumber.foreground": "#8686867c",
      "editorLineNumber.activeForeground": "#ffffffb2",
      "editorCursor.foreground": "#00f7ff",
      "editor.selectionBackground": "#ff00885d",
      "editor.inactiveSelectionBackground": "#8d8d8d62",
      "editor.lineHighlightBackground": "#28002b",
      "editorWidget.background": "#28002b",
      "editorWidget.border": "#00ffff33",
      "editorSuggestWidget.background": "#28002b",
      "editorSuggestWidget.border": "#00ffff33",
      "editorSuggestWidget.selectedBackground": "#00ffff33",
      "editorSuggestWidget.highlightForeground": "#00ffff",
      "focusBorder": "#00ffff",
      "editorBracketMatch.background": "#00000000",
      "editorBracketMatch.border": "#00000000",
      "editorBracketHighlight.foreground1": "#FFD700",
      "editorBracketHighlight.foreground2": "#DA70D6",
      "editorBracketHighlight.foreground3": "#179FFF",
      "editorBracketHighlight.foreground4": "#FFD700",
      "editorBracketHighlight.foreground5": "#DA70D6",
      "editorBracketHighlight.foreground6": "#179FFF",
      "editorBracketHighlight.unexpectedBracket.foreground": "#FF5370",
      "editor.snippetTabstopHighlightBackground": "#00000000",
      "editor.snippetTabstopHighlightBorder": "#00000000",
      "editor.snippetFinalTabstopHighlightBackground": "#00000000",
      "editor.snippetFinalTabstopHighlightBorder": "#00000000",
      "editor.wordHighlightBackground": "#00000000",
      "editor.wordHighlightBorder": "#00000000",
      "editor.wordHighlightStrongBackground": "#00000000",
      "editor.wordHighlightStrongBorder": "#00000000",
      "editor.selectionHighlightBackground": "#00000000",
      "editor.selectionHighlightBorder": "#00000000",
      "editorIndentGuide.background1": "#00000000",
      "editorIndentGuide.background2": "#00000000",
      "editorIndentGuide.background3": "#00000000",
      "editorIndentGuide.background4": "#00000000",
      "editorIndentGuide.background5": "#00000000",
      "editorIndentGuide.background6": "#00000000",
      "editorIndentGuide.activeBackground1": "#00000000",
      "editorIndentGuide.activeBackground2": "#00000000",
      "editorIndentGuide.activeBackground3": "#00000000",
      "editorHoverWidget.border": "#00ffff33",
    },
  });
}
